CREATE DATABASE IF NOT EXISTS `piclinic` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE `piclinic`;
CREATE USER 'CTS-user'@'localhost' IDENTIFIED BY 'YOURPASSWORD';
GRANT FILE, SHOW DATABASES, CREATE TEMPORARY TABLES, LOCK TABLES, SHOW VIEW, EXECUTE ON  *.* TO 'CTS-user'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON piclinic.* TO 'CTS-user'@'localhost';
FLUSH PRIVILEGES;
SHOW GRANTS for 'CTS-user'@'localhost';
